---

- name: download cuda deb
  get_url:
    url: {{ cuda_dl_url }}
    sha256sum: {{ csum }}
    dest: {{ cuda_dest }}

- name: dpkg cuda deb
  command: dpkg -i {{ cuda_dest }}

- name: install cuda
  apt:
    pkg: "{{ item }}"
    update_cache: yes
  with_items:
    - linux-image-extra-virtual
    - cuda
